BackendBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
                default: ''
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        surname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        password:
            type: string
            nullable: false
            length: 32
            options:
                fixed: true
                default: ''
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    lifecycleCallbacks: {  }
